apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-ozi
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: myapp-ozi
    spec:
      containers:
      - name: myapp
        image: nigelpoulton/pluralsight-docker-ci:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
