apiVersion: v1
kind: Pod
metadata:
  name: myapp-ozi
  labels:
    name: myapp-ozi-label
spec:
  containers:
  - name: myapp-ozi-ctr
    image: nigelpoulton/pluralsight-docker-ci:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
